### ISSUE TITLE
Why the character not  on the zero point

### ISSUE THREAD

**Issue by kevink2424** [softcat477/SMPL-to-FBX#7]
Hi @softcat477 

Thank you for ur code.

Why the character which generate from your code, not on the zero point in Blender?
 
<img width="422" alt="image" src="https://user-images.githubusercontent.com/97677638/171381690-14a3cd9e-8dc3-4988-b492-0f4ac70e85e7.png">

**Comment by softcat477** [comment]
It's because the `smlp_trans` is not normalized by `smpl_scale`. I didn't include this step in this repo, so you see the offset in blender.

You could try to do something like `smpl_trans`/`smpl_scale` to fix the offset.
fyi: here are details about the pkl file: https://google.github.io/aistplusplus_dataset/download.html
