### ISSUE TITLE
fbx-python problem

### ISSUE THREAD

**Issue by Andyen512** [softcat477/SMPL-to-FBX#8]
Hi, I met an error about fbx-python, do you know how to solve it?
/SMPL-to-FBX/FbxReadWriter.py", line 35, in __init__
    raise Exception("An error occured while loading the scene :(")
Exception: An error occured while loading the scene :(

**Comment by softcat477** [comment]
Hey I am able to to convert the example pkl file into fbx using this: `python3 Convert.py --input_pkl_base <pkl_path> --fbx_source_path <fbx_path>/SMPL_m_unityDoubleBlends_lbs_10_scale5_207_v1.0.0.fbx --output_base <output_path>`. Please provide details (step by step) to replicate your issue.

**Comment by tomerfr** [comment]
I encounter the same error.
Could you please provide assistance in resolving this issue?
Thank you

**Comment by tomerfr** [comment]
Make sure that fbx_source_path includes the total path of the fbx model file including the file itself, i.e. it ends with ".fbx"

**Comment by softcat477** [comment]
I haven't tried there methods, you may need to figure it out.

So this repo is sort of specifically designed to convert the SMPL representation in AIST++ dataset to fbx. For any other projects that use the SMPL representation, as long as they use, or you can figure out the way to convert their SMPL representation to AIST++'s (24 joints axis-angle rotation, and mind the joint order!) and put them into pkl files, then there's a chance that this repo could work.

I think in ROMP's publication, they mentioned something about `Instead of using the full 24 joints of the original SMPL model, we drop the last two hand joints.` You may need to figure out what's going on and is there a way to convert their SMPL into AIST++'s SMPL.

By the way, I think both ROMP and VIBE provide python scripts to convert their predicted results into fbx, maybe give it a try?
